rvm: '2.6.0'
cache: bundler

deploy:
  provider: heroku
  api_key:
    secure: "GHBP0+5avhBrXh5yKibec1UFGn/ttb5M97/jVCzBdInOdMo/JFt/bT7QQMnqqx+J/GesFGu6REIDz7/WD8KO86nYV3eN9QRUogngLy+4gjz8XyWVKrP8pdqWqTz5xIZ6+7Vc4D/KPB9iaRxiyG9cSjrMH86NO15FAVq7GqjNzKbsdZuPD6iaSSUJcj91WRZEkJTwFYMNXxfByyNuDJJ5c5IDfC1j2kEeHOP3TehJVxK7dsMsLklUorEjX0ISpkkCXL5VD9iKBotn9IdA1J/pOxDzWaI/3pb5PxPO3mRA+TNjAd6wc8LKRPpFczILkKXWgUWJ4VcgC2faIF08SXB+OWS6lF+V8QiIaND9lW6e1nc/Fwk6VvbJB8p5+z8R5aOgqtawQQuVjkhOPTqWw/XWfk49/NuzevFInmNaFj2BHpFdtA1nwDK0+JOOidGdPhjcaSeBFr65LRnEc1oz6y9sCRPUE1CqErQFRYUmHxkr+lt76/37o86xQD0K2yOJ9fOHAEXri/VbyBK9Bq8FqanvgotjdxV+qrIAWKqyYnDUkjmQepjviiGjwsp+nEt/LUd2MAQVKNZyFc5lXH6o2hZQZbkaZ8lh8TEqB6Alc4nzYWaduTpgAoGXn1hU2Q+AwN5HApz9TmopVdE7KLdvYwHFMzPwwE7MkLzX7GIqU9rcifo="

script:
  - mkdir -p spec && bundle exec rspec spec
  - rake db:test:prepare


before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq postgresql-server-dev-9.3

before_script:
   - psql -c 'create database pgapp_test;' -U postgres
